### ISSUE TITLE
Classification task gives relevance scores 0

### ISSUE THREAD

**Issue by ihiratanveer** [sbcblab/RelAgg#1]
Hi there, I am trying to implement this technique but it gives 0.5 probability for both classes (it's a binary classification task):
![image](https://user-images.githubusercontent.com/33114673/190143133-76785dce-a115-4f88-838d-0435cd191bfb.png)
which ends up giving me 0 scores for all the features:
![image](https://user-images.githubusercontent.com/33114673/190143292-8e293f3e-b9a0-4dc4-b3b8-05f6242b60af.png)
Could you please point out where am I going wrong?

**Comment by BrunoGrisci** [comment]
> Hi there, I am trying to implement this technique but it gives 0.5 probability for both classes (it's a binary classification task): ![image](https://user-images.githubusercontent.com/33114673/190143133-76785dce-a115-4f88-838d-0435cd191bfb.png) which ends up giving me 0 scores for all the features: ![image](https://user-images.githubusercontent.com/33114673/190143292-8e293f3e-b9a0-4dc4-b3b8-05f6242b60af.png) Could you please point out where am I going wrong?

Hi! The issue is with the training of your neural network, before the use of relevance aggregation. Make sure to use the adequate hyperparameters for the neural network (number of layers and neurons, regularization, number of training epochs, mini batch size, etc.) and to preprocess your dataset following the best practices of data science. You may want to check for instance if there are enough samples, if the two classes are imbalanced, if there are missing values, etc. Best regards.
